PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gcis: <http://data.globalchange.gov/gcis.owl#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT 
   (?author as ?ContributorID)
   (CONCAT(str(?ln), ", ", str(?gn)) as ?Name)
   (str(?rlabel) as ?Role)
   (str(?cht) as ?ChapterName)
   (?cn as ?ChapterNumber)
{
  ?report a gcis:Report .
  ?report dcterms:identifier "soccer" .
  ?report gcis:hasChapter ?chapter .
  ?chapter dcterms:title ?cht .
  ?chapter gcis:chapterNumber ?cn .
  ?chapter prov:qualifiedAttribution [ prov:hadRole ?role ; prov:agent ?author ] .
  ?role rdfs:label ?rlabel .
  ?author foaf:givenName ?gn .
  ?author foaf:lastName ?ln
} group by ?author
  order by ?cn
