jdk:
  - oraclejdk8
before_install:
  - wget http://archive.apache.org/dist/jena/binaries/apache-jena-3.0.0.tar.gz -O /tmp/apache-jena.tar.gz
  - tar xf /tmp/apache-jena.tar.gz
  - export PATH=$PATH:$PWD/apache-jena-3.0.0/bin
script: ./run-tests.sh
